### ISSUE TITLE
Setup Error on Anyline 3.8.1

### ISSUE THREAD

**Issue by arturmalek** [Anyline/anyline-ocr-examples-ios#10]

**Comment by peterAnyline** [comment]
Hello,

this looks like your Resources (AnylineResource.bundle) are not aligned with the correct version of the Anyline framework. Did you update also the AnylineResource.bundle files to the same version?

**Comment by arturmalek** [comment]
Hi Peter,

im using Cocoapods.Do i have to update the AnylineResource.bundle files manually?

Best Regards,
Artur
