### ISSUE TITLE
CoreNFC crash

### ISSUE THREAD

**Issue by akaraul** [Anyline/anyline-ocr-examples-ios#16]
On iPhone 6 with iOS 12.5.1 the application crashes:

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: /System/Library/Frameworks/CoreNFC.framework/CoreNFC | Referenced from: /private/var/containers/Bundle/Application/Frameworks/Anyline.framework/Anyline | Reason: image not found
Triggered by Thread:  0

**Comment by davlhd** [comment]
Hello, 
have you added the Anyline framework and chosen Embed & Sign?
You can find that option in the "General" tab of the application under "Frameworks, Libraries, and Embedded Content"

**Comment by akaraul** [comment]
@davlhd hi, Anlyline installed from pods

**Comment by davlhd** [comment]
Can you double check the setting?

**Comment by akaraul** [comment]
![Uploading image.png…]()

**Comment by akaraul** [comment]
Crash only on iOS 12.5.1 and so far it is known that only on iPhone 6. On other devices, everything is ok

**Comment by davlhd** [comment]
Thats strange. Can you please try to add it manually and see if that changes anything?

**Comment by akaraul** [comment]
I tried to run your sample project on an iPhone 5s with iOS 12. Got a crash again& @davlhd 
<img width="1512" alt="Screenshot 2021-03-04 at 10 44 38" src="https://user-images.githubusercontent.com/20819174/109928949-0c3bf180-7cd7-11eb-9b98-95bec2ad2b1f.png">

**Comment by akaraul** [comment]
Your app in the app store also crashes @davlhd 
https://user-images.githubusercontent.com/20819174/109933195-32b05b80-7cdc-11eb-9478-d7a0b98b20b8.MP4

**Comment by davlhd** [comment]
We opened a ticket for this issue and will hopefully be able to fix this in the upcoming release.

**Comment by akaraul** [comment]
@davlhd hi. when is the next release planned?

**Comment by davlhd** [comment]
The release is planned for this week

**Comment by akaraul** [comment]
@davlhd Hi. Is the problem fixed in the new release?

**Comment by davlhd** [comment]
Yes it should be fixed

**Comment by akaraul** [comment]
@davlhd But your app from the app store still crashes

**Comment by philippAnyline** [comment]
Hi @akaraul, short update from our side, sorry for the miscommunication: We are currently testing a fix for the core nfc crash and will release a hotfix as soon as possible. I hope we can get everything ready until Monday.

**Comment by akaraul** [comment]
@philippAnyline hi, thanks for the info

**Comment by akaraul** [comment]
@davlhd @philippAnyline the problem is fixed in version 29.1. Thanks
