### ISSUE TITLE
'Anyline/Anyline.h' file not found

### ISSUE THREAD

**Issue by mauryabip** [Anyline/anyline-ocr-examples-ios#18]
Issue in pod 'Anyline', '~> 27' or above
pod  '26' is not having US licence plate scan

Please let me know which pod version have US licence plate scan

**Comment by philippAnyline** [comment]
Hi @mauryabip, US LicensePlate scanning is only available since Anyline 29. I'd **recommend** to use **Anyline 29.1**

Regarding "Anyline.h not found": Since Anyline 27, the Anyline SDK has to be set to "Embed & Sign" in your target's "General" tab. Although cocoapods should configure that for you automatically. Please try out Anyline version 29.1 and let us know if your issue still persists. Thanks!

**Comment by philippAnyline** [comment]
If you are looking for features / fixes / improvements in the future, please check out our release notes [here](https://documentation.anyline.com/toc/platforms/ios/release_guide/index.html#release-notes-for-ios-version)

**Comment by mauryabip** [comment]
> Hi @mauryabip, US LicensePlate scanning is only available since Anyline 29. I'd **recommend** to use **Anyline 29.1**
> 
> Regarding "Anyline.h not found": Since Anyline 27, the Anyline SDK has to be set to "Embed & Sign" in your target's "General" tab. Although cocoapods should configure that for you automatically. Please try out Anyline version 29.1 and let us know if your issue still persists. Thanks!

@philippAnyline  i have used Anyline 29.1 but still getting same issue. Please look into this

**Comment by philippAnyline** [comment]
Could you please provide some details? Did the Anyline SDK ever work for you, or did you always have the issue with "Anyline.h" not found? Can you please send your podfile?

Another thing that you could try is: Delete your workspace, podfile.lock and the pods folder and run "pod repo update && pod install" again.

**Comment by mauryabip** [comment]
@philippAnyline 
I have tried your demo code and it is working fine. Now i am trying with pod and Anyline 26 is working fine but below pod throwing error
**Podfile:**
target 'PlateScanTest' do
  	#use_frameworks!
	pod ‘Anyline’

end

**Comment by philippAnyline** [comment]
What error do you get?

**Comment by mauryabip** [comment]
@philippAnyline  PFA of error

![Screenshot 2021-03-18 at 5 29 47 PM](https://user-images.githubusercontent.com/25147067/111622775-9627a680-880f-11eb-89ff-2c24654f3f43.png)

**Comment by renatoAnyline** [comment]
Hi @mauryabip, can you send me a picture of your build settings architecture tab

![image](https://user-images.githubusercontent.com/80908383/111653933-92445600-8808-11eb-84bb-ceca45e508c4.png)

in case you didn't do yet, delete the podfile.lock then try to run

`pod deintegrate`
`pod cache clean --all`

delete all remaining files related to pods in your project folder except for the Podfile

`pod install`

and uncomment `#use_frameworks!` line in the cocoapods

and let me know if any of this helps

**Comment by mauryabip** [comment]
@philippAnyline  I have tried again to add pod but same issue


![Screenshot 2021-03-19 at 10 23 53 AM](https://user-images.githubusercontent.com/25147067/111735895-c8ceaf00-88a2-11eb-9004-341f15fe376b.png)

**Comment by mauryabip** [comment]
@philippAnyline Please check Pod: Anyline 26.1 and above one is Pod: Anyline 29.1


![Screenshot 2021-03-19 at 12 01 21 PM](https://user-images.githubusercontent.com/25147067/111740639-1cdd9180-88ab-11eb-890c-484a1870335c.png)

**Comment by mauryabip** [comment]
Hi @renatoAnyline @philippAnyline

Any update over above issue

**Comment by aaronmchugh** [comment]
@mauryabip 
I was having the same problem with building iOS in Ionic but maybe your situation is different.
This solution worked for me with v26.1. 

Follow Philipps steps outlined above.

Add pod 'Anyline' to Podfile before adding plugin.

Run commands: 
ionic cordova plugin add io-anyline-cordova@26.1

ionic cordova build ios

Just in case anyone else is having the same issue with Ionic.

**Comment by anthonymediaconcepts** [comment]
Hi Anyline Team and fellow Dev Team

I have the same issue for 29.1 

We are updating the Anyline plugin to get ready for Production release, so a solution to this will be most appreciated 


@aaronmchugh , will try 26.1, but i think it will be good to use the latest release.


Thank you

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
