### ISSUE TITLE
SPM Support?

### ISSUE THREAD

**Issue by StefaniOSApps** [Anyline/anyline-ocr-examples-ios#19]
For some years now, CocoaPods has been increasingly being replaced by SPM. Newer projects often use Swift Package Manager. Have you already considered offering this for Anyline in the future?

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
