### ISSUE TITLE
arm64 support needed

### ISSUE THREAD

**Issue by StefaniOSApps** [Anyline/anyline-ocr-examples-ios#20]
If I want to integrate Anlyine directly on an M1 MacBook (without CocoaPods), I have to deactivate arm64. However, this leads to the problem that I can no longer run the project on the simulator.

Could not find module 'XXXXX' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator.

This problem persists even when I build all architectures.
Unfortunately, this problem is very widespread and from my point of view there is no other solution to this problem.

ref.
https://developer.apple.com/forums/thread/123614

**Comment by danielalbertini** [comment]
Hi,

currently the only known workaround to this is to exclude the arm64 architecture from your simulator build. Only downside is that the simulator will run a bit slower.

<img width="536" alt="Screenshot 2021-06-11 at 15 25 55" src="https://user-images.githubusercontent.com/1771071/121693510-8267a580-cac9-11eb-9d2b-93fee6e07874.png">

Best Regards,
Daniel

**Comment by janu75** [comment]
I have the same issue here.
On top of that, I use a different framework, which does not have (and normally wouldn't need) x64_86 support. 

So, having arm64 support would be very much appreciated.

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
