### ISSUE TITLE
How do manual capture 

### ISSUE THREAD

**Issue by Bharath2r** [Anyline/anyline-ocr-examples-ios#22]
we are using like this  -             self.scanView = ALScanView.init(
                frame: view.bounds,
                scanViewPlugin: documentScanViewPlugin,
                cameraConfig: ALCameraConfig.defaultDocument()!,
                flashButtonConfig: ALFlashButtonConfig.defaultFlash())

for ALDocumentScanViewPlugin

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
