### ISSUE TITLE
Crash due to UIAlertView being unavailable 

### ISSUE THREAD

**Issue by ypleskach** [Anyline/anyline-ocr-examples-ios#24]
I've integrated Anyline SDK v34 and got the following runtime crash (exception):

```
*** Terminating app due to uncaught exception 'NSObjectNotAvailableException', reason: 'UIAlertView is deprecated and unavailable for UIScene based applications, please use UIAlertController!'
terminating with uncaught exception of type NSException
```

Are there any plans on migrating to UIAlertController? Do you have timelines for it? This is a major blocker for us as we can't use the framework at all

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
