### ISSUE TITLE
BitCode Issue with Anyline

### ISSUE THREAD

**Issue by rameshinnov** [Anyline/anyline-ocr-examples-ios#26]
Hi Team,

Earlier we maintained Bitcode as disabled and we don't find any issues.

Now we need to enabled bit code in our project  and we found issues that Anyline does not contain bit code enabled.

Please share us the bit code enabled frameworks or any other solution to solve it.

Version info:
ANYLINE SDK version 35
Xcode: 12.1

Thanks,
Ramesh

**Comment by berndkamplanyline** [comment]
Hi @rameshinnov!

We don't actively monitor the Github Issues, please raise a support request using the [Anyline Helpdesk](https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6).
When raising a support request based on this Github Issue, please fill out and include the following information:

```
Support request concerning Anyline Github Repository: anyline-ocr-examples-ios
```

Thank you!

**Comment by renatoAnyline** [comment]
Hi @rameshinnov,

As of today our architecture does not support bitcode enabled and we there is no way around it, sorry for the inconvenience.

Thank you
