### ISSUE TITLE
Are there any plans to add SPM support?

### ISSUE THREAD

**Issue by ypleskach** [Anyline/anyline-ocr-examples-ios#28]
Swift Package Manager is already widely adopted and becoming the defacto standard for at least all new projects.
Are there plans to add SPM support to the Anyline SDK?

**Comment by berndkamplanyline** [comment]
Hi @ypleskach!

Support for Swift Package Manager will actually come with the next release 🎉

For the future inquiries please use our [Anyline Helpdesk Portal](https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6), because we don't actively monitor the Github Issues. 

Thank you!
