### ISSUE TITLE
ANYLINE is unable to scan DataMatrix

### ISSUE THREAD

**Issue by rameshinnov** [Anyline/anyline-ocr-examples-ios#31]
Hi AnyLine Team,

App is able to scan QR code, but is not scanning DataMatrix.   Seen in release history, this  feature has been added in older AnyLine versions.

Version info:
ANYLINE SDK version 35
Xcode: 13

Thanks,
Ramesh

**Comment by berndkamplanyline** [comment]
Hi @rameshinnov,

We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
